### ISSUE TITLE
format colapsed for sqldeveloper 21.4.0.346

### ISSUE THREAD

**Issue by wienerri** [Trivadis/plsql-formatter-settings#171]
Format colapsed in sqldevloper 21.4.0.346 and plsql-formatter-setting-main.zip file from 15.12.2021

Error in console:
Symbol 'xmlelement[41,54)' not found
Symbol 'xmlelement[58,78)' not found
Symbol 'JSON_OBJECT' not found
incrementalAlignments callback: null
java.lang.reflect.InvocationTargetException

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at oracle.dbtools.arbori.Program.javaCallback(Program.java:1349)

        at oracle.dbtools.arbori.Program.access$200(Program.java:60)

        at oracle.dbtools.arbori.Program$PredicateCmd.eval(Program.java:1466)

        at oracle.dbtools.arbori.Program.eval(Program.java:1267)

        at oracle.dbtools.app.Format.format(Format.java:375)

        at oracle.dbtools.raptor.config.CustomFormat.format(CustomFormat.java:28)

        at oracle.dbtools.raptor.config.FormatSQLOptionsPanel.updatePreview(FormatSQLOptionsPanel.java:654)

        at oracle.dbtools.raptor.config.FormatSQLAdvancedOptions.valueChanged(FormatSQLAdvancedOptions.java:374)

        at javax.swing.JTree.fireValueChanged(JTree.java:2934)

        at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)

        at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)

        at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)

        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)

        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)

        at javax.swing.JTree.setSelectionPath(JTree.java:1641)

        at oracle.dbtools.raptor.config.FormatSQLAdvancedOptions.<init>(FormatSQLAdvancedOptions.java:165)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

        at javax.ide.util.MetaClass.newInstance(MetaClass.java:145)

        at oracle.dbtools.raptor.standalone.IndexedPreferencesCommand$IndexPreferencesTask.doWork(IndexedPreferencesCommand.java:122)

        at oracle.dbtools.raptor.standalone.IndexedPreferencesCommand$IndexPreferencesTask.doWork(IndexedPreferencesCommand.java:65)

        at oracle.dbtools.raptor.backgroundTask.RaptorTask.call(RaptorTask.java:199)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at oracle.dbtools.raptor.backgroundTask.RaptorTaskManager$RaptorFutureTask.run(RaptorTaskManager.java:702)

        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.NullPointerException

        at oracle.dbtools.app.Format.incrementalAlignments(Format.java:823)

        ... 35 more

Symbol 'xmlelement[41,54)' not found

Symbol 'xmlelement[58,78)' not found

Symbol 'JSON_OBJECT' not found

incrementalAlignments callback: null

java.lang.reflect.InvocationTargetException

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at oracle.dbtools.arbori.Program.javaCallback(Program.java:1349)

        at oracle.dbtools.arbori.Program.access$200(Program.java:60)

        at oracle.dbtools.arbori.Program$PredicateCmd.eval(Program.java:1466)

        at oracle.dbtools.arbori.Program.eval(Program.java:1267)

        at oracle.dbtools.app.Format.format(Format.java:375)

        at oracle.dbtools.raptor.config.CustomFormat.format(CustomFormat.java:28)

        at oracle.dbtools.raptor.config.FormatSQLOptionsPanel.updatePreview(FormatSQLOptionsPanel.java:654)

        at oracle.dbtools.raptor.config.FormatSQLAdvancedOptions.valueChanged(FormatSQLAdvancedOptions.java:374)

        at javax.swing.JTree.fireValueChanged(JTree.java:2934)

        at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)

        at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)

        at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)

        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)

        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)

        at javax.swing.JTree.setSelectionPath(JTree.java:1641)

        at oracle.dbtools.raptor.config.FormatSQLAdvancedOptions.<init>(FormatSQLAdvancedOptions.java:165)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

        at javax.ide.util.MetaClass.newInstance(MetaClass.java:145)

        at oracle.ide.javaxide.Util.createInstance(Util.java:60)

        at oracle.ide.javaxide.Util.createInstance(Util.java:40)

        at oracle.ide.extension.LazyClassAdapter.createInstance(LazyClassAdapter.java:65)

        at oracle.ide.config.ExtensionSettingsPage.newTraversable(ExtensionSettingsPage.java:106)

        at oracle.ide.config.ExtensionNavigable.newTraversable(ExtensionNavigable.java:87)

        at oracle.ide.panels.MetaTraversable.newTraversable(MetaTraversable.java:219)

        at oracle.ide.panels.MDDPanel.getTraversable(MDDPanel.java:1390)

        at oracle.ide.panels.MDDPanel.access$800(MDDPanel.java:129)

        at oracle.ide.panels.MDDPanel$Tsl.updateSelectedNavigable(MDDPanel.java:1653)

        at oracle.ide.panels.MDDPanel$Tsl.updateSelection(MDDPanel.java:1561)

        at oracle.ide.panels.MDDPanel$Tsl.actionPerformed(MDDPanel.java:1555)

        at javax.swing.Timer.fireActionPerformed(Timer.java:313)

        at javax.swing.Timer$DoPostEvent.run(Timer.java:245)

        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)

        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)

        at java.awt.EventQueue.access$500(EventQueue.java:97)

        at java.awt.EventQueue$3.run(EventQueue.java:709)

        at java.awt.EventQueue$3.run(EventQueue.java:703)

        at java.security.AccessController.doPrivileged(Native Method)

        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)

        at oracle.javatools.internal.ui.EventQueueWrapper._dispatchEvent(EventQueueWrapper.java:169)

        at oracle.javatools.internal.ui.EventQueueWrapper.dispatchEvent(EventQueueWrapper.java:151)

        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)

        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)

        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)

        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)

        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)

        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)

        at java.security.AccessController.doPrivileged(Native Method)

        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)

        at java.awt.Dialog.show(Dialog.java:1084)

        at java.awt.Component.show(Component.java:1671)

        at java.awt.Component.setVisible(Component.java:1623)

        at java.awt.Window.setVisible(Window.java:1014)

        at java.awt.Dialog.setVisible(Dialog.java:1005)

        at oracle.bali.ewt.dialog.JEWTDialog.runDialog(JEWTDialog.java:399)

        at oracle.bali.ewt.dialog.JEWTDialog.runDialog(JEWTDialog.java:360)

        at oracle.ide.dialogs.WizardLauncher.runDialog(WizardLauncher.java:55)

        at oracle.ide.panels.TDialogLauncher.showDialog(TDialogLauncher.java:225)

        at oracle.ide.config.IdeSettings.showDialog(IdeSettings.java:875)

        at oracle.ide.config.IdeSettings.showDialog(IdeSettings.java:612)

        at oracle.dbtools.raptor.standalone.IndexedPreferencesCommand$IndexPreferencesTask.invokeLater(IndexedPreferencesCommand.java:219)

        at oracle.dbtools.raptor.standalone.IndexedPreferencesCommand$IndexPreferencesTask$WaitOver$1.run(IndexedPreferencesCommand.java:231)

        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)

        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)

        at java.awt.EventQueue.access$500(EventQueue.java:97)

        at java.awt.EventQueue$3.run(EventQueue.java:709)

        at java.awt.EventQueue$3.run(EventQueue.java:703)

        at java.security.AccessController.doPrivileged(Native Method)

        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)

        at oracle.javatools.internal.ui.EventQueueWrapper._dispatchEvent(EventQueueWrapper.java:169)

        at oracle.javatools.internal.ui.EventQueueWrapper.dispatchEvent(EventQueueWrapper.java:151)

        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)

        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)

        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)

        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Caused by: java.lang.NullPointerException

        at oracle.dbtools.app.Format.incrementalAlignments(Format.java:823)

**Comment by PhilippSalvisberg** [comment]
> With SQL Developer 21.4 and a fresh download and import of the SQL Developer trivadis_advanced_format.xml and trivadis_advanced_format.abori files following the directions in the repo, a CTRL-F7 on the following statement gives me this output... 

I can reproduce this with a fresh install using JDK8. The output in the settings looks like this when importing the settings:

![image](https://user-images.githubusercontent.com/3883171/146428429-262ac553-1232-42e2-8cde-2cc265e36b5c.png)

I currently do not understand why this happens. However, a workaround is to configure JDK11 instead of JDK8 in the `product.conf` file. 

On Windows I've added the following line in `%APPDATA%\sqldeveloper\21.4.0\product.conf` :

```
SetJavaHome C:\app\jdk-11.0.12
```

And on macOS I've added the following line in `$HOME/.sqldeveloper/21.4.0/product.conf`:

```
SetJavaHome /Users/phs/Applications/graalvm-ce-java11-21.2.0/Contents/Home
```

The GraalVM JDK contains a faster JavaScript engine. You feel the difference when using the formatter on larger files.

After a restart of SQLDev the preference dialog looks like this:

![image](https://user-images.githubusercontent.com/3883171/146430124-b26e1c8b-ba59-42f5-a589-216127a26e23.png)

**Comment by RichardSoule** [comment]
Set JavaHome C:\Program Files\Java\jdk-11.0.12 in the product.conf file wasn't working for me.

Set JavaHome "C:\Program Files\Java\jdk-11.0.12" seems to kind of work. If I import just the XML, then everything appears to more or less be working. But if I then add in the .abori file it goes back to a 'collapsed' format.

**Comment by PhilippSalvisberg** [comment]
In this case I would try the 8.3 format to avoid escaping spaces in the directory name. Something like this:

```
Set JavaHome C:\PROGRA~1\Java\jdk-11.0.12
```

You can check the JDK in SQLDev in the About dialog.

![image](https://user-images.githubusercontent.com/3883171/146438020-7991989c-6447-40b4-9d2c-def69954d3c8.png)

**Comment by PhilippSalvisberg** [comment]
It looks JavaScript callback functions do not work in an Arbori program when running under JDK8. It's an issue introduced by SQLDev 20.4.0 and 20.4.1. This worked in previous versions.

And the formatter uses JavaScript callback functions for almost all Arbori query result. As a result the formatter puts just a single space between lexical tokens.

I consider this a SQLDEV bug. The workaround is to use JDK 11 instead of JDK 8.

**Comment by RichardSoule** [comment]
I had to download the SQL Developer without the JDK to get my Java(TM) Platform to 11.0.12.

I imported both files and it's basically working, but it is a bit different than it used to be.

I'm getting some strange stuff with the query I posted above. For some reason, two of the CTE clauses are appearing on a single line instead of on two lines.
`with target_list as (
      select unique target_name, metric_column, target_guid, metric_guid
        from mgmt$target_type
       where target_type
             in ('oracle_pdb', 'oracle_database')
         and metric_name = 'tbspAllocation'
         and metric_column in ('spaceUsed', 'spaceAllocated')
   ),
   space_used_list as (select * from target_list where metric_column = 'spaceUsed'),
   space_allocated_list as (select * from target_list where metric_column = 'spaceAllocated'), last_night_space_used as (
      select mgmt$metric_daily.target_name,
             target_guid,
             round(sum (average / 1024)) as total_current_used_gb
        from mgmt$metric_daily
        join space_used_list
       using (target_guid, metric_guid)
       where rollup_timestamp = trunc(systimestamp - interval '1' day)
       group by mgmt$metric_daily.target_name, target_guid
   ),
   last_night_space_allocated as (
      select mgmt$metric_daily.target_name, target_guid, round(sum (average / 1024)) as total_current_allocated_gb
        from mgmt$metric_daily
        join space_allocated_list
       using (target_guid, metric_guid)
       where rollup_timestamp = trunc(systimestamp - interval '1' day)
       group by mgmt$metric_daily.target_name, target_guid
   ), last_month_space_used as (
      select mgmt$metric_daily.target_name, target_guid, round(sum (average / 1024)) as total_last_month_used_gb
        from mgmt$metric_daily
        join space_used_list
       using (target_guid, metric_guid)
       where rollup_timestamp = trunc(add_months(systimestamp, - 1))
       group by mgmt$metric_daily.target_name, target_guid
   ), six_month_ago_space_used as (
      select mgmt$metric_daily.target_name, target_guid, round(sum (average / 1024)) as total_six_month_ago_used_gb
        from mgmt$metric_daily
        join space_used_list
       using (target_guid, metric_guid)
       where rollup_timestamp = trunc(add_months(systimestamp, - 6))
       group by mgmt$metric_daily.target_name, target_guid
   ),
   results as (
      select last_night_space_allocated.target_name,
             total_current_allocated_gb as current_allocated_gb,
             total_current_allocated_gb - total_current_used_gb as current_free_gb,
             total_current_used_gb as current_used_gb,
             total_last_month_used_gb as last_month_used_gb,
             total_six_month_ago_used_gb as six_month_ago_gb,
             total_current_used_gb - total_last_month_used_gb as last_month_growth_gb,
             total_current_used_gb - total_six_month_ago_used_gb as six_month_growth_gb,
             round((total_current_used_gb - total_six_month_ago_used_gb) / 6) as average_six_month_growth
        from last_night_space_allocated
        join last_night_space_used
       using (target_guid)
        join last_month_space_used
       using (target_guid)
        join six_month_ago_space_used
       using (target_guid)
   ) select *
  from results
 order by last_month_growth_gb
       desc;`

**Comment by PhilippSalvisberg** [comment]
> I had to download the SQL Developer without the JDK to get my Java(TM) Platform to 11.0.12.
> 
> I imported both files and it's basically working, but it is a bit different than it used to be.
> 
> I'm getting some strange stuff with the query I posted above. For some reason, two of the CTE clauses are appearing on a single line instead of on two lines.
> 
> <img alt="image" width="1046" src="https://user-images.githubusercontent.com/14116398/146444528-04ba1287-45fd-4348-ba62-41313f4ed089.png">

Could you please open a dedicated issue for this one? Thank you.

**Comment by PhilippSalvisberg** [comment]
Posted a related question in the SQLDev forum: https://community.oracle.com/tech/developers/discussion/4492626/arbori-javascript-callback-functions-do-not-work-in-sqldev-21-4-0-21-4-1-with-jdk8-why .

**Comment by wienerri** [comment]
Due to new oracle JAVA licensing model, I have got prohibition to use JDK higher then 8

**Comment by PhilippSalvisberg** [comment]
Arbori JavaScript callback functions do not work in SQLDev 21.4.0, 21.4.1 and SQLcl 21.4.0 when using JDK 8.  If you are not ready to use another JDK, you have to stay with the older versions of SQLDev and SQLcl.

**Comment by PhilippSalvisberg** [comment]
@wienerri 
>I tired OpenJDK version 1.17. There are much more warnings in console, but formating still colapsed.

SQLDev cannot be used with JDK 17 without losing functionality. For example, JavaFx and Nashorn have been removed. The latter is required for the formatter (or another JS engine). We have to wait until Oracle bundles the necessary libraries with SQLDev. Then it should work with JDK 17 as well. But right now, SQLDev is not designed to work with JDK 17. So, no need to try...

Since Arbori callback functions are broken in SQLDev with JDK 8 the only option is to to use older versions of SQLDev or to use a JDK 11 distribution. IMO every JDK 11 distribution should work.

As mentioned before, to get the best runtime performance I recommend to use GraalVM Community 21.3.0 based on Open JDK 11.  See https://www.graalvm.org/downloads/

**Comment by wienerri** [comment]
Version with java11 - https://www.graalvm.org/downloads/ - seems to be working OK.

**Comment by PhilippSalvisberg** [comment]
Thanks @wienerri for the feedback. I'm going to close the issue, since it's a SQLDev bug.
