### ISSUE TITLE
Regression on Windows using json configuration file

### ISSUE THREAD

**Issue by florian-caton** [Trivadis/plsql-formatter-settings#172]
Hi Philipp, 

I tried the latest version of the jar, and i'm getting the following error when using a json configuration file :

```
Exception in thread "main" javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: instantiate on java.io.File failed due to: no applicable overload found (overloads: [Method[public java.io.File(java.lang.String)], Method[public java.io.File(java.net.URI)], Method[public java.io.File(java.io.File,java.lang.String)], Method[public java.io.File(java.lang.String,java.lang.String)]], arguments: [JavaObject[Path\To\My\File.extension (sun.nio.fs.WindowsPath)] (HostObject)])
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:483)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:460)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:400)
        at com.trivadis.plsql.formatter.TvdFormat.run(TvdFormat.java:33)
        at com.trivadis.plsql.formatter.TvdFormat.main(TvdFormat.java:42)
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: instantiate on java.io.File failed due to: no applicable overload found (overloads: [Method[public java.io.File(java.lang.String)], Method[public java.io.File(java.net.URI)], Method[public java.io.File(java.io.File,java.lang.String)], Method[public java.io.File(java.lang.String,java.lang.String)]], arguments: [JavaObject[Path\To\My\File.extension (sun.nio.fs.WindowsPath)] (HostObject)])
        at <js>.existsDirectory(<eval>:166)
        at <js>.getRelevantFiles(<eval>:68)
        at <js>.run(<eval>:530)
        at <js>.:program(<eval>:599)
        at org.graalvm.polyglot.Context.eval(Context.java:379)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458)
        ... 3 more
```

I think `format.js` is affected too,

Best regards

**Comment by PhilippSalvisberg** [comment]
Could you please explain the problem step by step so that I get a chance to reproduce it myself? Please provide also versions of your OS and JDK. Thank you.

**Comment by florian-caton** [comment]
I'm using the `tvdformat.jar` file to format sql code on commit on git repositories, with the hook you provided as an example.

Basically, it's just a command line call such as 
```
java -jar .git/hooks/tvdformat.jar C:/TEMP/myTempFile.json ext=sql,prc,fnc,pks,pkb,trg,vw,tps,tpb,tbp,plb,pls,rcv,spc,tys,tyb,typ,aqt,aqp,ctx,dbl,tab,dim,snp,con,collt,seq,syn,grt,sp,spb,sps,pck mext=markdown,mdown,mkdn,md xml=.format/trivadis_advanced_format.xml arbori=.format/trivadis_custom_format.arbori
```

Regarding the os : Windows 7 SP1

Regarding the java version used, here is the information :

```
$ java -version
java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
```
The previous version (`https://github.com/Trivadis/plsql-formatter-settings/releases/download/sqldev-21.2.1/tvdformat.jar`) works well on this environment.

I'll check on a different environment next week, with Windows 10. I do not have the possibility to try it now.

**Comment by PhilippSalvisberg** [comment]
@florian-caton Thank you for the details. I understand the problem now and can reproduce it on macOS. Therefore it is not Windows specific. Furthermore the JDK does not matter. Same result with JDK 8, 11, 17. 

It seems to be a problem with the standalone formatter only. Using the script from SQLcl seems to work. 

I guess this problem is related to the latest GraalVM JS engine 21.3.0. But I have to verify that.
