### ISSUE TITLE
Error message when calling tvdformat the first time in SQLcl 20.3

### ISSUE THREAD

**Issue by PhilippSalvisberg** [Trivadis/plsql-formatter-settings#70]
When using tvdformat with settings for SQLDev 20.2 in SQLcl 20.3 error messages are printed on the console saying that certain symbols are not found.

Here's an example:

```
SQLcl: Release 20.3 Production on Sat Oct 31 14:28:28 2020

Copyright (c) 1982, 2020, Oracle.  All rights reserved.

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.9.0.0.0


SQL> select * from dept;

    DEPTNO DNAME          LOC          
---------- -------------- -------------
        10 ACCOUNTING     NEW YORK     
        20 RESEARCH       DALLAS       
        30 SALES          CHICAGO      
        40 OPERATIONS     BOSTON       

SQL> tvdformat *

Formatting SQLcl buffer... Symbol 'create_view#[104,120)' not found
Symbol 'create_view#[107,114)' not found
Symbol 'create_view#[104,120)' not found
done.
  1  SELECT *
  2*   FROM dept;
```

**Comment by PhilippSalvisberg** [comment]
The reason is that SQLcl 20.3 comes with an updated parser version. The Arbori program based on the parser in 20.2 uses symbols that do not exist in the newer parser anymore. Hence there are some error messages when loading the Arbori program the first time. 

It is not clear what the impact is exactly. However, the best approach is to use the Arbori program provided in 20.3 and apply the changes made. It's likely that some whitespace handling issues are fixed in this version of the formatter as well.  

The

**Comment by PhilippSalvisberg** [comment]
Everything needed for the formatter is in `dbtools-common.jar`. The same jar file is used in SQL Developer. However, it is not possible to patch an existing SQLDev 20.2 installation by replacing this jar file. As soon as you connect to a database the following error is thrown:

```
java.lang.NoClassDefFoundError: oracle.dbtools.db.VersionTracker
	at oracle.dbtools.thirdparty.AmazonRedshift.AmazonRedshiftConnectionRecognizer.createConnectionInfo(AmazonRedshiftConnectionRecognizer.java:43)
	at oracle.dbtools.raptor.navigator.ObjectFactoryRegistry.createConnectionInfo(ObjectFactoryRegistry.java:230)
	at oracle.dbtools.raptor.navigator.ObjectFactoryRegistry.createFactory(ObjectFactoryRegistry.java:163)
	at oracle.dbtools.raptor.navigator.ObjectFactoryRegistry.getFactory(ObjectFactoryRegistry.java:153)
	at oracle.dbtools.raptor.navigator.db.impl.DatabaseTreeNode.getObjectFactory(DatabaseTreeNode.java:91)
	at oracle.dbtools.raptor.navigator.db.impl.DatabaseTreeNode$LoadTask.doWork(DatabaseTreeNode.java:145)
	at oracle.dbtools.raptor.navigator.db.impl.DatabaseTreeNode$LoadTask.doWork(DatabaseTreeNode.java:119)
	at oracle.dbtools.raptor.backgroundTask.RaptorTask.call(RaptorTask.java:199)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at oracle.dbtools.raptor.backgroundTask.RaptorTaskManager$RaptorFutureTask.run(RaptorTaskManager.java:702)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The class is in the jar file, but I guess the OSGi bundle version does not match and that leads to this error message.

AFAIK there are no plans to release a SQLDev 20.3 version. This repository provides formatter settings primarily for SQLDev. They can be applied for the corresponding SQLcl version. It is a new situation that we have a SQLcl version without a corresponding SQLDev version.

I guess the most sensible thing to do is to postpone this fix until a new version of SQLDev with a corresponding/compatible SQLcl version is available.

**Comment by PhilippSalvisberg** [comment]
I did some tests and the conclusion is that the formatter settings for SQLDev 20.2 are not compatible with SQLcl 20.3. The formatter result might be wrong even if no error is shown.

On this branch https://github.com/Trivadis/plsql-formatter-settings/tree/bugfix/issue-70-sqlcl-20.3 the settings are provided that work with SQLcl 20.3.0. However, I do not plan to merge this to the main branch as long as no SQLDev version is available for these settings.
